version: '3.8'

services:
  # Web Application Service (Hotspot QRIS)
  app:
    build:
      context: https://github.com/dmtshop20/AdilanetSystem.git#main
      dockerfile: Dockerfile
    container_name: hotspot_qris_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SQL_HOST=mariadb
      - SQL_PORT=3306
      - SQL_USER=root
      - SQL_PASSWORD=MySecurePassword123!
      - SQL_ADMIN_USER=root
      - SQL_ADMIN_PASSWORD=MySecurePassword123!
      - SQL_DB_NAME=hotspot_db
      - SANPAY_MODE=Simulation
    networks:
      - mikhmon_network

networks:
  mikhmon_network:
    external: true
